import Navbar from "@/components/Navbar";
import Head from "next/head";
import AboutPage from "./About";
import HomePage from "./Home";
import PortfolioPage from "./Portfolio";
import SkillsPage from "./Skills";

interface Props {
  isDarkMode: boolean;
  setDarkMode: () => void;
}

export default function Home({ isDarkMode, setDarkMode }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar setDarkMode={setDarkMode} isDarkMode={isDarkMode} />
      <HomePage />
      <AboutPage />
      <SkillsPage />
      <PortfolioPage />
    </>
  );
}
